/* Inline everything into one file, twice.
 *
 *   node tools/build.mjs
 *     -> dist/aloud.html      a complete document; opens from the filesystem,
 *                             copies to a phone, works with the network off
 *     -> dist/artifact.html   the same page as a body fragment, because the
 *                             Artifact host supplies its own doctype and head
 *
 * Same source for both. A strict-CSP host blocks every external request, so
 * the build fails rather than ship a page that silently loses its stylesheet.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

let html = readFileSync(join(ROOT, 'index.html'), 'utf8');

// A narration generated by tools/monologue.mjs travels inside the page, so the
// single file still has something to read when there is no bridge to poll.
const narrationPath = join(ROOT, 'narration.json');
let narrationNote = 'none';
if (existsSync(narrationPath)) {
  const raw = readFileSync(narrationPath, 'utf8');
  let parsed = null;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    console.error('build: narration.json is not valid JSON — ' + err.message);
    process.exit(1);
  }
  const beats = Object.values(parsed.modes || {}).reduce((n, m) => n + (m.beats || []).length, 0);
  narrationNote = `${Object.keys(parsed.modes || {}).length} mode(s), ${beats} beats`;

  // </script> inside JSON would close the tag early; < is the same string
  // to a JSON parser and inert to the HTML tokeniser.
  const safe = JSON.stringify(parsed).replace(/</g, '\\u003c');
  html = html.replace('<script src="js/split.js"></script>',
    `<script>window.TTS=window.TTS||{};window.TTS.NARRATION=${safe};</script>\n<script src="js/split.js"></script>`);
}

html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g, (_, href) =>
  `<style>\n${readFileSync(join(ROOT, href), 'utf8')}\n</style>`);

html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) =>
  `<script>\n${readFileSync(join(ROOT, src), 'utf8')}\n</script>`);

if (/<script[^>]+src=|<link[^>]+href=/.test(html)) {
  console.error('build: an external reference survived inlining');
  process.exit(1);
}

// --- the fragment ------------------------------------------------------------
// Title and stylesheet come along; the doctype, <html>, <head> and <body> do
// not, because the host writes those itself.

const style = html.match(/<style>[\s\S]*?<\/style>/);
const title = html.match(/<title>([\s\S]*?)<\/title>/);
const body = html.match(/<body[^>]*>([\s\S]*)<\/body>/);

if (!style || !title || !body) {
  console.error('build: could not find the title, style or body to lift out');
  process.exit(1);
}

const fragment = [
  `<title>${title[1]}</title>`,
  style[0],
  body[1].trim(),
  ''
].join('\n');

// The lookahead matters: <header> is legitimate content, <head> is not.
if (/<!DOCTYPE|<html(?![a-z])|<head(?![a-z])|<body(?![a-z])/i.test(fragment)) {
  console.error('build: the fragment still carries document structure');
  process.exit(1);
}

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, 'aloud.html'), html);
writeFileSync(join(DIST, 'artifact.html'), fragment);

const kb = (s) => (s.length / 1024).toFixed(1) + ' kB';
console.log(`built dist/aloud.html    (${kb(html)})`);
console.log(`built dist/artifact.html (${kb(fragment)})`);
console.log(`narration baked in: ${narrationNote}`);
